### ISSUE TITLE
기능구현 - 관리자/상품등록(admin/product/register)

### ISSUE THREAD

**Issue by chhak2021** [hochmun/Kmarket#36]
- http://localhost:8080/Kmarket/admin/product/register.do
- 스토리보드 개발 가이드 참고

**Comment by chhak2021** [comment]
데이터베이스 설계가 끝난 후 바로 관리자/상품등록 기능 구현 바랍니다. by 김철학

**Comment by hochmun** [comment]
- [ ] 카테고리 불러오기 1차 분류, 2차분류 (get)
- [ ] 게시물 등록 기능 완성하기 (post)
 // 나중에 완성해야 할것
- [ ]  유효성 검사 넣기
- [ ] 들어가는 파일 크기 체크

**Comment by hochmun** [comment]
2022/12/09 심규영 - 관리자/상품등록 기능 구현 완료

**Comment by hochmun** [comment]
수정 해야할것

- [ ]  포인트 할인율 적용 확인
- [ ]  이미지 저장 경로 변경 (aws 저장 경로로 변경)
- [ ]  게시물 등록 기능 서블릿 방식으로 변경 (이미지 저장 카테고리별로 지정)
- [ ]  상품 등록 완료시 완료 알림 추가 (알림기능 페이지 추가 예정)
- [ ]  할인율 0~100 까지만 입력 가능하게 수정
- [ ]  셀러 입력 없애기 (다른 페이지 완성후? 테스트가 더 이상 필요 없을때)

**Comment by hochmun** [comment]
추가 하면 좋은 기능

- [ ]  2차 카테고리 까지 고른 후 고른 상품 종류에 따라 입력 가능(추가 입력 해야 하는 것, 입력 해야 할 필요 없는 것) 영역 바꾸기(동적)?

**Comment by hochmun** [comment]
2022/12/23 심규영 관리자/상품등록 => 셀러 입력 없애기 완료
