### ISSUE TITLE
상품 데이터 입력

### ISSUE THREAD

**Issue by chhak2021** [hochmun/Kmarket#38]
- 관리자/상품등록 기능구현이 완료 후 상품데이터 입력하기
- 각 카테고리별 상품 데이터 입력하기
- 각 카테고리별 최소 10개 이상 입력하기(모든 팀원 1명당 3개이상 카테고리 담당)
- 상품 데이터와 이미지는 오픈마켓(Gmarket) 참고하기

**Comment by hochmun** [comment]
- [ ]  10/10 브랜드 여성의류
- [ ]  10/11 브랜드 남성의류
- [ ]  10/12 브랜드 진/캐쥬얼
- [ ]  10/13 브랜드 신발/가방
- [ ]  10/14 브랜드 쥬얼리/시계
- [ ]  10/15 브랜드 아웃도어
- [ ]  11/10 여성의류
- [ ]  11/11 남성의류
- [ ]  11/12 언더워어
- [ ]  11/13 신발
- [ ]  11/14 가방/잡화
- [ ]  11/15 쥬얼리/시계
- [ ]  11/16 화장품/향수
- [ ]  11/17 바디/헤어
- [ ]  12/10 출산/육아
- [ ]  12/11 장난감/완구
- [ ]  12/12 유아동 의류
- [ ]  12/13 유아동 신발/잡화
- [ ]  13/10 신선식품
- [ ]  13/11 가공식품
- [ ]  13/12 건강식품
- [ ]  13/13 커피/음료
- [ ]  13/14 생필품
- [ ]  13/15 바디/헤어
- [ ]  14/10 가구/DIY
- [ ]  14/11 침구/커튼
- [ ]  14/12 조명/인테리어
- [ ]  14/13 생활용품
- [ ]  14/14 주방용품
- [ ]  14/15 문구/사무용품
- [ ]  14/16 사무기기
- [ ]  14/17 악기/취미
- [ ]  14/18 반려동물용품
- [ ]  15/10 노트북/PC
- [ ]  15/11 모니터/프린터
- [ ]  15/12 PC주변기기
- [ ]  15/13 모바일/태블릿
- [ ]  15/14 카메라
- [ ]  15/15 게임
- [ ]  15/16 영상가전
- [ ]  15/17 주방가전
- [ ]  15/18 계절가전
- [ ]  15/19 생활/미용가전
- [ ]  15/20 음향가전
- [ ]  15/21 건강가전
- [ ]  16/10 스포츠의류/운동화
- [ ]  16/11 휘트니스/수영
- [ ]  16/12 구기/라켓
- [ ]  16/13 골프
- [ ]  16/14 자전거/보드/기타레저
- [ ]  16/15 캠핑/낚시
- [ ]  16/16 등산/아웃도어
- [ ]  16/17 건강/의료용품
- [ ]  16/18 건강식품
- [ ]  16/19 렌탈서비스
- [ ]  17/10 자동차용품
- [ ]  17/11 공구/안전/산업용품
- [ ]  18/10 여행/항공권
- [ ]  18/11 도서/음반/e교육
- [ ]  18/12 공연티켓
- [ ]  18/13 e쿠폰
- [ ]  18/14 상품권
