### ISSUE TITLE
기능구현 - 회원/판매자가입(member/registerSeller)

### ISSUE THREAD

**Issue by hochmun** [hochmun/Kmarket#83]
- http://localhost:8080/Kmarket/member/registerSeller.do
- 스토리보드 개발 가이드 참고

**Comment by asdeqqga** [comment]
- [ ] 일반 회원가입 데이터 DB연동 완료
- [ ] 아이디 중복확인 기능 구현
- [ ]  입력 데이터 유효성 검사 기능 구현
- [ ] zipcode 다음 우편번호 서비스 연동
- [ ]  주소입력 기능 구현

**Comment by asdeqqga** [comment]
유효성 검사 

- [ ] ceo
- [ ] email

**Comment by asdeqqga** [comment]
- [ ] DB - addr1 , manager , managerHp 수정
- [ ] 대표자 유효성 수정
